name: Push to Inviz GOOGLE ARTIFACT Registry
on:
  push:
    branches:
      - "**"
      - "!main"

jobs:        
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY1: ${{ secrets.KEY1}}
      SERVICE_ACCOUNT_KEY2: $ {{ secrets.KEY2 }}
    steps:
      - name: gcloud sdk
        run: |
          touch temp.json
          echo $SERVICE_ACCOUNT_KEY1 > temp.json
          echo $SERVICE_ACCOUNT_KEY2 > clust.json
          sudo snap install google-cloud-cli --classic
          gcloud auth activate-service-account tf-owner@search-tf-test.iam.gserviceaccount.com --key-file=clust.json --project=search-tf-test
	    gcloud config set account tf-owner@search-tf-test.iam.gserviceaccount.com
          sudo snap install kubectl --classic
	    gcloud container clusters get-credentials saas-gke-cluster1 --region asia-south1 --project search-tf-test
          kubectl create secret docker-registry staging-secrets \
	    --docker-server=https://asia-docker.pkg.dev \
          --docker-email=staging-master-service-account@search-artifacts.iam.gserviceaccount.com \
          --docker-username=_json_key \
          --docker-password="$(cat temp.json)" -n dev-search
          
          #sudo snap install kubectl --classic
          #gcloud config set project search-tf-test
          gcloud container clusters get-credentials saas-gke-cluster1 --region asia-south1 --project search-tf-test
          
